# GENERATED BY LLM

import random

def generate_random_sudoku(N=9, clues_ratio=0.35):
    """
    Tạo ngẫu nhiên một bài toán Sudoku N x N đảm bảo 100% SATISFIABLE.
    :param N: Kích thước bàn cờ (Ví dụ: 9)
    :param clues_ratio: Tỷ lệ số lượng ô cho sẵn (VD: 0.35 tương đương ~28 ô)
    """
    subN = int(N ** 0.5)

    # 1. Tạo bàn cờ hoàn chỉnh cơ sở (Base Valid Pattern)
    def pattern(r, c):
        return (subN * (r % subN) + r // subN + c) % N

    def shuffle(s):
        return random.sample(s, len(s))

    # Xáo trộn các hàng và cột trong từng khối subgrid
    rBase = range(subN)
    rows = [g * subN + r for g in shuffle(rBase) for r in shuffle(rBase)]
    cols = [g * subN + c for g in shuffle(rBase) for c in shuffle(rBase)]
    nums = shuffle(range(1, N + 1))

    # Tạo bàn cờ đã điền kín số hợp lệ
    solved_board = [[nums[pattern(r, c)] for c in cols] for r in rows]

    # 2. Xóa bớt số ngẫu nhiên để tạo đề bài (Clues)
    num_cells = N * N
    num_clues = int(num_cells * clues_ratio)
    num_holes = num_cells - num_clues

    puzzle = [row[:] for row in solved_board]
    holes = random.sample(range(num_cells), num_holes)

    for h in holes:
        r = h // N
        c = h % N
        puzzle[r][c] = 0  # Gán về ô trống

    return puzzle